/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WalletImport } from './routes/wallet'
import { Route as StatisticsImport } from './routes/statistics'
import { Route as PaymentsImport } from './routes/payments'
import { Route as MessagesImport } from './routes/messages'
import { Route as LoginImport } from './routes/login'
import { Route as DiscordImport } from './routes/discord'
import { Route as IndexImport } from './routes/index'
import { Route as DocumentImoprt } from "./routes/document";
import { Route as CodeImport } from "./routes/code";

// Create/Update Routes

const CodeRoute = CodeImport.update({
  path: '/code',
  getParentRoute: () => rootRoute,
} as any)

const DocumentRoute = DocumentImoprt.update({
  path: '/document',
  getParentRoute: () => rootRoute,
} as any)

const WalletRoute = WalletImport.update({
  path: '/wallet',
  getParentRoute: () => rootRoute,
} as any)

const StatisticsRoute = StatisticsImport.update({
  path: '/statistics',
  getParentRoute: () => rootRoute,
} as any)

const PaymentsRoute = PaymentsImport.update({
  path: '/payments',
  getParentRoute: () => rootRoute,
} as any)

const MessagesRoute = MessagesImport.update({
  path: '/messages',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DiscordRoute = DiscordImport.update({
  path: '/discord',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof CommentsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesImport
      parentRoute: typeof rootRoute
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsImport
      parentRoute: typeof rootRoute
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsImport
      parentRoute: typeof rootRoute
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletImport
      parentRoute: typeof rootRoute
    }
    '/document': {
      id: '/document'
      path: '/document'
      fullPath: '/document'
      preLoaderRoute: typeof DocumentImoprt
      parentRoute: typeof rootRoute
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  DiscordRoute,
  LoginRoute,
  MessagesRoute,
  PaymentsRoute,
  StatisticsRoute,
  WalletRoute,
  DocumentRoute,
  CodeRoute
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/comments",
        "/login",
        "/messages",
        "/payments",
        "/statistics",
        "/wallet"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/comments": {
      "filePath": "comments.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/messages": {
      "filePath": "messages.tsx"
    },
    "/payments": {
      "filePath": "payments.tsx"
    },
    "/statistics": {
      "filePath": "statistics.tsx"
    },
    "/wallet": {
      "filePath": "wallet.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
